pipeline {
    agent any
    environment {
        DOCKER_PASSWORD = credentials("docker_password")
        GITHUB_TOKEN = credentials("github_token")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }
        stage('docker push') {
            steps {
                script {
                    def imageName = "gdarius405/hello-img:1.1.0"
                    sh "docker login -u gdarius405 -p ${DOCKER_PASSWORD}"
                    sh "docker push ${imageName}"
                }
            }
        }
    }
}
