global:
  resolve_timeout: 1m

route:
  group_by: ['UserAlerts']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'dafitew719@astimei.com'
    from: 'ghercadarius@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'ghercadarius@gmail.com'
    auth_identity: 'ghercadarius@gmail.com'
    auth_password: ''
